#!/bin/bash
git clone git@git.generalassemb.ly:/DSI-SYD-2/11.4.1_ModelDeployment.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_mahendra.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_jeff.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_yen.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Capstone.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_srikanta.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_eric.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_byron.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_ilona.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/11.1.2_InterviewPrep.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_greg.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_indu.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.4.1_timeseries-intro_to_timeseries-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_jed.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_eddie.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.3.1_statistics-maximum_likelihood_estimation-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_roshan.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project4_uploads.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_adrian.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_joel.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_kinah.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_sharleen.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/capstone_tom.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project_Tableau_ExtraCredit.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.1.2_cloud-hadoop_big_data-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Reviews.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/cheat_sheets.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project4.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.4.2_naive-bayes-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.3.1_clustering-dbscan_from_scratch-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.2.1_clustering-cluster_evaluation_metrics-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.2.1_trees-CARTs-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.4.1_pca-intro-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.3.3_clustering-intro_to_clustering_kmeans-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project3_uploads.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.4.1_python-intro_to_webscraping-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.4.2_pca-intro-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.5.3_clustering-battle_of_clusterers-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.3.3_optimization-gridsearch_hyperparameters-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project2_uploads.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.1.3_optimization-gradient_descent-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.1.1_optimization-feature_selection-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.5.1_svm-support_vector_machines-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.5.1_evaluation-classifiers_confusion_matrix_roc-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.4.1_classification-logistic_regression-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.3.1_classification-knn_intro_to_classification-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.1.1_bayes-intro_to_bayesian_stats-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.2.3_ensemble-intro_to_ensembles_bagging-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.3.2_ensemble-boosting_adaboost-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.3.1_regression-object_oriented_programming-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.3.2_evaluation-cross_validation_train_test-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.4.3_naive-bayes-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.2.1_preprocessing-feature_scaling-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.1.1_regression-simple_linear_regression-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project1.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/11.2.1_presentation-tips.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/11.1.1_nnet-intro_to_neural_networks_backpropagation-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/whiteboard_photos.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.3.3_timeseries-intro_to_timeseries-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.4.2_timeseries-autocorrelation-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.4.3_timeseries-arma-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.5.1_timeseries-arima_aic_forecasting-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.5.2_timeseries-arima-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.1.1_pca-svd-faces-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project1_uploads.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.2.2_trees-CARTs-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.5.2_svm-support_vector_machines-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.1.3_python-pipelines_in_sklearn-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.1.2_pca-visualization-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.2.3_pca-extra-practice-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.5.2_nlp-twitter_api_case_study-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.3.1_nlp-topic_modeling_lda-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.3.2_nlp-topic_modeling_lda-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.4.1_nlp-sentiment_analysis-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.4.2_nlp-sentiment_analysis-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.5.1_nlp-nlp_techniques_overview-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.1.2_nlp-intro_to_nlp-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.1.3_nlp-intro_to_nlp-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.3.1_ensemble-build_randomforest_from_scratch-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.3.4_clustering-intro_to_clustering_kmeans-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.4.1_clustering-hierarchical_clustering-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.3.2_clustering-dbscan-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/8.2.2_clustering-cluster_evaluation_metrics-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.2.2_cloud-intro_to_spark-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.2.3_cloud-intro_to_spark-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.1.1_cloud-intro_to_big_data-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/9.2.1_cloud-intro_to_aws-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.1.3_bayes-priors_posteriors_baseball-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.2.2_bayes-intro_to_pymc3-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.2.3_bayes-intro_to_pymc3-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.2.1_bayes-gelman_election-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.1.2_bayes-conjugacy_beta_binomial-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/10.3.2_bayes-ab_testing-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Home.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/PechaKucha_uploads.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.1.3_database-postgresql_practice-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.5.1_database-sql_commands_together-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.5.1_database-sql_with_pandas_2-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.2.1_eda-basic_eda_walkthrough-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.2.2_eda-group_projects_1-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.5.2_eda-group_projects_2-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.4.1_eda-music_data_blogging-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.4.2_pandas-concatenation_joining_data-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.3.4_pandas-data_munging_full_overview-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.1.2_pandas-long_wide_pivot_melt-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.1.1_pandas-long_wide_pivot_melt-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.3.3_statistics-bootstrapping-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.4.2_statistics-error_types_power_analysis-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.3.1_statistics-hypothesis_testing_ttest_pvalues-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.1.1_PechaKucha_week2.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project3.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.5.1_statistics-central_limit_theorem-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.3.1_python-list_comprehensions-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/Project2.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.2.2_python-functions-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.2.1_python-types_lists_dicts-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.2.3_ElainasStatisticsBasics.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.2.1_statistics-bias_variance_tradeoff-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.2.2_regression-sklearn_statsmodels_intro-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.1.2_regression-simple_linear_regression-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.2.3_regression-regularization_kobe_shots-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.2.2_regression-regularization-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.2.3_regression-mlr_assumptions_statsmodels-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.1.3_regression-linear_regression_from_scratch-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.4.1_regression-discrimination_group_project-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/7.1.1_python-webscraping_opentable-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.4.3_python-webscraping_lincoln_quotes-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.5.1_python-web_services_apis-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.5.2_python-web_services_apis-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.4.2_python-practice_xpath_webscraping-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.3.4_optimization-gridsearch_hyperparameters-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.3.1_optimization-gradient_descent-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.1.2_optimization-feature_selection-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/4.3.3_evaluation-cross_validation_train_test-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.5.2_evaluation-classifiers_confusion_matrix_roc-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.4.2_classification-logistic_regression-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/5.3.2_classification-knn_intro_to_classification-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/6.3.2_classification-knn_imputation-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/3.3.2_statistics-review_clt_confidence_hypothesis_testing-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.2.3_pandas-grouping-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.1.2_pandas-data_in_pandas_intro-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.1.3_pandas-data_in_pandas_intro-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.2.2_eda-visualization_intro-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.2.1_eda-data_cleaning_intro-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.4.1_database-sql_with_pandas_1-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.3.1_database-sql_connecting_to_databases-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/2.2.4_database-database_fundamentals-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.1.2_tools-git_intro-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.1.1_tools-command_line-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.4.1_statistics-fundamentals_intro-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.4.2_statistics-describing_data-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.5.2_statistics-confidence_intervals-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.3.2_python-movies_data_structures-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.1.3_python-iteration_control_functions-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.3.3_python-descriptive_statistics_numpy-lesson.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.3.4_python-descriptive_statistics_numpy-lab.git
git clone git@git.generalassemb.ly:/DSI-SYD-2/1.4.3_probability-foundations_combinations_permutations-lesson.git
